### ISSUE TITLE
Command line flag --strict is undocumented

### ISSUE THREAD

**Issue by bgagnon** [instrumenta/kubeval#113]
There is no mention of the `--strict` flag anywhere in the README (particularly the Usage section):

https://github.com/garethr/kubeval/blob/master/cmd/root.go#L114

**Comment by garethr** [comment]
Thanks for flagging. I'll get this documented.

**Comment by garethr** [comment]
I've added this to the docs at https://kubeval.instrumenta.dev/#strict-schemas
