### ISSUE TITLE
`kubeval --version` gives empty version

### ISSUE THREAD

**Issue by tholok97** [instrumenta/kubeval#125]
After following the [installation instructions](https://kubeval.instrumenta.dev/installation) (using curl instead of wget) and running `kubeval --version` I get no value for the actual version.

## Environment

Attempted in CentOS and Ubuntu 18.10

## Steps to reproduce

```bash
curl -sSL -O https://github.com/instrumenta/kubeval/releases/download/0.9.2/kubeval-linux-amd64.tar.gz
tar xf kubeval-linux-amd64.tar.gz
mv kubeval /usr/local/bin
kubeval --version
```
Gives output:
```text
Version:      
Git commit:   
Built:        
Go version:   go1.12.2
OS/Arch:      linux/amd64
```

**Comment by garethr** [comment]
Thanks for flagging, I managed to break in moving over to goreleaser. Will get fixed up.

**Comment by garethr** [comment]
Should be fixed in https://github.com/instrumenta/kubeval/commit/a048e1a23fed0ed13c90011ebf01691fe0c4aefa which will be in the next release.
