### ISSUE TITLE
Change exit code if schema can't be located

### ISSUE THREAD

**Issue by WillPlatnick** [instrumenta/kubeval#126]
Hello,
I'd like to propose a change to the existing behavior:

We currently use kubeval to evaluate every manifest before it's deployed. The problem is we have plenty of custom CRD's that kubeval doesn't have schemas for.

Currently, the behavior is to exit with an error code of 1 if a manifest evaluates improperly or if it can't locate the proper schema. I'd like to propose adding a specific exit code to indicate that a schema couldn't be found to verify against. Once it has its own error, we can safely catch that in our CI process and not have it block deployments.

**Comment by garethr** [comment]
Thanks, this is a good idea I think. It will definitely help some users. Also discussing not issuing an error code if you pass a flag in https://github.com/instrumenta/kubeval/pull/127

**Comment by garethr** [comment]
You can now skip missing schemas with the `--skip-missing-schemas` flag in 0.11.0 which should resolve your issue.
