### ISSUE TITLE
Getting 404 Error When Validating

### ISSUE THREAD

**Issue by fatherlinux** [instrumenta/kubeval#131]
[root@rhel7 wordpress-demo]# kubeval wordpress-objects.yaml 
3 errors occurred:
	* Problem loading schema from the network at https://kubernetesjsonschema.dev/master-standalone/route-v1.json: Could not read schema from HTTP, response status is 404 Not Found
	* Problem loading schema from the network at https://kubernetesjsonschema.dev/master-standalone/imagestream-v1.json: Could not read schema from HTTP, response status is 404 Not Found
	* Problem loading schema from the network at https://kubernetesjsonschema.dev/master-standalone/deploymentconfig-v1.json: Could not read schema from HTTP, response status is 404 Not Found

Thoughts?

**Comment by garethr** [comment]
Ah, these aren't Kubernetes objects, but specific to OpenShift. I need to update https://github.com/garethr/openshift-json-schema which I've let get fairly behind.

**Comment by garethr** [comment]
To clarify here, if you have Openshift object you can use the `--openshift` flag on `kubeval` which should pick up the relevant schemas.

**Comment by nusrath432** [comment]
@garethr Still seeing similar error with F5 CRDs 

Ref: https://github.com/F5Networks/k8s-bigip-ctlr/issues/2873#issuecomment-1561964862
