### ISSUE TITLE
Missing customresourcedefinition-apiextensions-v1beta1.json: 404 Not Found

### ISSUE THREAD

**Issue by undeadops** [instrumenta/kubeval#140]
Hi,

I was trying to run kubeval on on my git repo of kubernetes manifests (for CI tests), and I ran into an error:

```
1 error occurred:
	* Problem loading schema from the network at https://kubernetesjsonschema.dev/master-standalone/customresourcedefinition-apiextensions-v1beta1.json: Could not read schema from HTTP, response status is 404 Not Found
```

Looking through directories, this one has it: https://github.com/instrumenta/kubernetes-json-schema/tree/master/v1.13.3

But the associated standalone one is missing it: https://github.com/instrumenta/kubernetes-json-schema/tree/master/v1.13.3-standalone

**Comment by garethr** [comment]
Kubeval now has a flag to work around this, as of 0.11.0 you can pass `--ignore-missing-schema` to work around this problem.
