### ISSUE TITLE
Feature Request: --skip-kind flag

### ISSUE THREAD

**Issue by ian-howell** [instrumenta/kubeval#151]
This feature request is in reference to @garethr's quote https://github.com/instrumenta/kubeval/pull/127#issuecomment-496242202 regarding skipping schema validation for CRDs (paraphrased):

> Having an explicit list of resources to skip validation would be good as well, but could come later if preferred... even if the main usecase might be for CRDs it would work with any resource types. Maybe `--skip-kind`?

This flag would accept a comma-separated list of resource names, then proceed to skip schema-validation for any matching resources.

**Comment by garethr** [comment]
Thanks for the suggestion and the PR. Now merged in #152
