### ISSUE TITLE
Resources requests/limits fails to validate when providing the number of CPUs as Numbers

### ISSUE THREAD

**Issue by jacksontj** [instrumenta/kubeval#161]
This is very similar to #22 (almost identical). When I run validation I get the following error:

```
---> spec.template.spec.containers.1.resources.limits: Must validate one and only one schema (oneOf)
---> spec.template.spec.containers.1.resources.limits: Invalid type. Expected: [string,null], given: number
---> spec.template.spec.containers.1.resources.requests: Must validate one and only one schema (oneOf)
---> spec.template.spec.containers.1.resources.requests: Invalid type. Expected: [string,null], given: number
```

I did check and the schema I'm testing against (https://github.com/instrumenta/kubernetes-json-schema/blob/master/v1.10.9-standalone/pod.json#L983) does have the fix from #22 -- but the value is being interpreted as a number not an integer. This is because the value is:

```
                     "requests": {
                        "cpu": 3.5,
```

Which k8s seems happy to apply, so it seems that the schema needs to support string, integer, and "number".

**Comment by jacksontj** [comment]
To clarify, If I wrap my values in strings they seem to work fine -- I'm reporting soely because this is a mismatch in behavior between kubeval and the k8s API.

**Comment by brendanjryan** [comment]
I am experiencing this issue as well -- 

It seems like a deeper issue due to restrictions in the internal k8s api which aim to ensure this number is _never_ actually represented as a float. 

https://godoc.org/k8s.io/apimachinery/pkg/api/resource#Quantity
```
Examples:

1.5 will be serialized as "1500m"
1.5Gi will be serialized as "1536Mi"
Note that the quantity will NEVER be internally represented by a floating point number. That is the whole point of this exercise.
```

Would you be open to an opstream patch in [openapi2jsonschema](https://github.com/instrumenta/openapi2jsonschema) adding support for this (pinned behind the `kubernetes` flag)?

**Comment by brendanjryan** [comment]
Fix implemented here -- https://github.com/instrumenta/openapi2jsonschema/pull/27 

If this is accepted we will have to regen all of the schemas 🙆‍♂

**Comment by garethr** [comment]
This should now be resolved in the master schemas, ie. those used if you don't specify a version. If you could verify that fixes your problem I'll update the rest of the versions.

**Comment by brendanjryan** [comment]
Running the patched version on master seems to fix *half* of the issues - but there is still a `oneof` violation 🤔

Example resource:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: myimage
    resources:
      requests:
        cpu: 2.0
      limits:
        cpu: 5.0
```

Output:
```console
⇒  docker run -it -v `pwd`/fixtures:/fixtures garethr/kubeval -v 1.15.0 fixtures/*

1 error occurred:
	* Failed initalizing schema https://kubernetesjsonschema.dev/v1.15.0-standalone/pod-v1.json: Could not read schema from HTTP, response status is 404 Not Found


⇒  docker run -it -v `pwd`/fixtures:/fixtures garethr/kubeval -v 1.14.4 fixtures/*

The file fixtures/Pod.yaml contains a valid Pod
```

I think this conflict results from overlap in the "numeric" `json-schema` type ([ref](https://json-schema.org/understanding-json-schema/reference/numeric.html)). What do you think @garethr ?

**Comment by brendanjryan** [comment]
https://github.com/instrumenta/openapi2jsonschema/pull/28

**Comment by garethr** [comment]
I've merged and republished the master schemas for this fix.
