### ISSUE TITLE
Kubeval does not work for kubernetes version 1.13.7

### ISSUE THREAD

**Issue by PeterUherek** [instrumenta/kubeval#170]
I run this command:

kubeval -v 1.13.7
1 errors occurred:
	* Problem loading schema from the network at https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/v1.13.7-standalone/service.json: Could not read schema from HTTP, response status is 404 Not Found

Is there way how to generate schema for this kubernetes version?

**Comment by garethr** [comment]
Ah, this looks like this you have old version of kubeval?

If you upgrade to the latest version, 0.13.0, this should be resolved.

**Comment by PeterUherek** [comment]
Thx :)
