### ISSUE TITLE
Stuck reading from stdin when using --directories

### ISSUE THREAD

**Issue by Pharb** [instrumenta/kubeval#184]
`kubeval  --directories=/tmp/kubeval-input` does not work properly for me when running it in my CI pipeline.

It seems to be stuck reading from stdin, even though I only want it to read from `--directories`.

My current workaround is to run it like this to switch to the "not-stdin" branch of the code:
`kubeval  --directories=/tmp/kubeval-input /dev/null`

I guess there might be something wrong here: https://github.com/instrumenta/kubeval/blob/0.14.0/main.go#L68

Here are all the options I'm using:
```
kubeval --strict --kubernetes-version=1.14.6 --skip-kinds=CustomResourceDefinition,Prometheus,PrometheusRule,ServiceMonitor,Alertmanager --schema-location=file:///opt/kubeval-schemas --directories=/tmp/kubeval-input
```

Thanks for this nice tool 🎉

**Comment by stevesim101** [comment]
I have the exact same problem.  Thank you @Pharb for the workaround!

**Comment by maltoe** [comment]
Same here, thank you @Pharb

**Comment by fredleger** [comment]
same here don't get why this is like this.
ex:

a) from command line in the ci container:

`$ kubeval -d manifests --ignore-missing-schemas`

produce 
```
PASS - chaoskube/templates/serviceaccount.yaml contains a valid ServiceAccount
PASS - chaoskube/templates/clusterrole.yaml contains a valid ClusterRole
PASS - chaoskube/templates/clusterrolebinding.yaml contains a valid ClusterRoleBinding
PASS - chaoskube/templates/role.yaml contains a valid Role
PASS - chaoskube/templates/rolebinding.yaml contains a valid RoleBinding
PASS - chaoskube/templates/deployment.yaml contains a valid Deployment
...
```

In non interactive run in the ci (using same container)

`$ kubeval -d manifests --ignore-missing-schema`

produce

```
WARN - Set to ignore missing schemas
PASS - stdin contains an empty YAML document
```

I could just guess that there is some relation with the terminal not being a tty but it should not rely on that i think.

**Comment by DannyBen** [comment]
Thanks for this issue and workaround. 
I spent the last 30 minutes trying to figure it out - it is easily reproducible on GitHub actions.

Thanks in advance for the fix - I see there is already a PR in progress.
