### ISSUE TITLE
Add option to ignore SSL error when downloading schemas

### ISSUE THREAD

**Issue by johnowl** [instrumenta/kubeval#197]
I'm behind a corporate proxy and I receive an error when try to use kubeval, it would be nice if the tool had an option to disable SSL verification, like `wget --no-check-certificate` or `curl -I` option.

`$ kubeval deployment.yaml
kubernetes-deployment.yaml: Failed initalizing schema https://kubernetesjsonschema.dev/master-standalone/deployment-apps-v1beta2.json: Get https://kubernetesjsonschema.dev/master-standalone/deployment-apps-v1beta2.json: x509: certificate signed by unknown authority`

**Comment by romankor** [comment]
i got that to run by 
```
kubeval --additional-schema-locations https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/
```

**Comment by jnmcfly** [comment]
or in case of using apline just `apk update \
    && apk add ca-certificates \
    && rm -rf /var/cache/apk/*`
