### ISSUE TITLE
[bug] empty objects pass

### ISSUE THREAD

**Issue by brandonkal** [instrumenta/kubeval#206]
This YAML document passes:
```yaml
apiVersion: apps/v1
kind: Deployment
```
Looking at the JSON schema, I see that neither spec of metadata.name is required. Can we not trust the OpenAPI schema?

**Comment by garethr** [comment]
This will fail if you pass the `--strict` flag, which enforces the missing properties.

```
ERR  - file.yaml Missing 'metadata' key
```
