### ISSUE TITLE
Provide verbose output on errors

### ISSUE THREAD

**Issue by alexizmailov** [instrumenta/kubeval#211]
```
$ kubeval -v 1.13.10 --ignore-missing-schemas 1.yaml
WARN - Set to ignore missing schemas
ERR  - 1.yaml: Missing 'kind' key

$ ll -h 1.yaml
-rw-r--r--  1 user  staff   485K  7 Feb 14:17 1.yaml
```

The file is 485K and all I have is `Missing 'kind' key`. 

Would be nice to have `-v` option that shows at least the line number where that key is missing.

**Comment by Linus-Boehm** [comment]
See also instrumenta/kubeval#56

**Comment by alexizmailov** [comment]
Dup of https://github.com/instrumenta/kubeval/issues/56
