### ISSUE TITLE
[NetworkPolicy] Failed initializing schema for `networkpolicies.networking.k8s.io`

### ISSUE THREAD

**Issue by sc250024** [instrumenta/kubeval#213]
## Description

In our CI/CD pipeline, we're receiving errors from KubeVal that it cannot find the associated `NetworkPolicy` JSON schema definitions, even though they exist.

## Expected Behavior

Kubeval, or the JSON schema repository, should support `NetworkPolicy` objects.

## Actual Behavior

All attempts to validate against a schema fail. See below.

## Steps to Reproduce the Problem

- Download the latest stable version of KubeVal (**v0.14.0**)
- Create the following YAML file locally:

```yaml
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: release-name
spec:
  ingress:
  - from:
    - podSelector: {}
  podSelector:
    matchLabels: {}
  policyTypes:
  - Ingress
```

- Run any of the following commands (all of them fail):

```console
$ kubeval --kubernetes-version '1.14.8' test.yaml

ERR  - test.yaml: Failed initalizing schema https://kubernetesjsonschema.dev/v1.14.8-standalone/networkpolicy-networking-v1.json: Could not read schema from HTTP, response status is 404 Not Found

$ kubeval --kubernetes-version '1.15.7' test.yaml

ERR  - test.yaml: Failed initalizing schema https://kubernetesjsonschema.dev/v1.15.7-standalone/networkpolicy-networking-v1.json: Could not read schema from HTTP, response status is 404 Not Found

$ kubeval --kubernetes-version '1.16.4' test.yaml

ERR  - test.yaml: Failed initalizing schema https://kubernetesjsonschema.dev/v1.16.4-standalone/networkpolicy-networking-v1.json: Could not read schema from HTTP, response status is 404 Not Found

$ kubeval --kubernetes-version '1.17.0' test.yaml

ERR  - test.yaml: Failed initalizing schema https://kubernetesjsonschema.dev/v1.17.0-standalone/networkpolicy-networking-v1.json: Could not read schema from HTTP, response status is 404 Not Found
```

I'm a bit confused because all of the files exist in the repository:

- https://github.com/instrumenta/kubernetes-json-schema/blob/master/v1.14.8-standalone/networkpolicy-networking-v1.json
- https://github.com/instrumenta/kubernetes-json-schema/blob/master/v1.15.7-standalone/networkpolicy-networking-v1.json
- https://github.com/instrumenta/kubernetes-json-schema/blob/master/v1.16.4-standalone/networkpolicy-networking-v1.json
- https://github.com/instrumenta/kubernetes-json-schema/blob/master/v1.17.0-standalone/networkpolicy-networking-v1.json

## Specifications

  - Version: **kubeval 0.14.0**
  - Platform: macOS

**Comment by yannh** [comment]
Hi @sc250024 , is this still an issue? Using a kubeval built from master, I can not reproduce this:

$ kubeval --kubernetes-version 1.14.8  fixtures/network-policy.yaml 
PASS - fixtures/network-policy.yaml contains a valid NetworkPolicy

**Comment by tredfield** [comment]
I am getting same issue

```
kubeval --kubernetes-version 1.14.8 result.yml
ERR  - device-api/templates/ingress.yaml: Failed initializing schema https://kubernetesjsonschema.dev/v1.14.8-standalone/ingress-networking-v1.json: Could not read schema from HTTP, response status is 404 Not Found
```

**Comment by carlossg** [comment]
works in 0.15.0

```
 kubeval --kubernetes-version '1.17.0' - <<EOF
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: release-name
spec:
  ingress:
  - from:
    - podSelector: {}
  podSelector:
    matchLabels: {}
  policyTypes:
  - Ingress
EOF
PASS - stdin contains a valid NetworkPolicy (release-name)
```
