### ISSUE TITLE
Extremely slow with large input

### ISSUE THREAD

**Issue by dewe** [instrumenta/kubeval#216]
Running `kubeval` with larger multi-document files (e.g. output from kustomize build) takes extremely long time most of the time. Thjs started a month ago, or more. Occasionally it works as fast as it used to. 

```bash
$ kustomize build https://github.com/coreos/kube-prometheus > tmp.yaml
$ time kubeval tmp.yaml --ignore-missing-schemas
WARN - Set to ignore missing schemas
PASS - tmp.yaml contains a valid Namespace
...
WARN - tmp.yaml containing a ServiceMonitor was not validated against a schema

real	1m56.956s 🤯
user	0m1.237s
sys	0m0.451s
```

Same thing happens if I pipe yaml into kubeval stdin.

Most of the time it seems to be waiting for kubernetesjsonschema.dev:443, which is responding with transfer speeds as low as 1 KB/s. I have tested this from different networks, same results.

**Comment by yannh** [comment]
Hi @dewe , are you still experiencing this with the latest builds?

**Comment by dewe** [comment]
Haven't tried that for a while -- we switched to a local cache to workaround this issue.

**Comment by dewe** [comment]
Did a few shots right now, it seems to work fine now. Couldn't say definitely that it's gone, but it was quick enough right now.

**Comment by yannh** [comment]
@dewe there were issues with caching of schemas which I believe to now be solved. I suspect your large file required downloading many different schemas - and that might have been slow.

**Comment by dewe** [comment]
Yeah, sound reasonable. With kustomize build we're declaring the entire cluster, hundreds of resources. 

Closing this issue.
