### ISSUE TITLE
I received an error after my initial install and today I am no longer seeing this error

### ISSUE THREAD

**Issue by evanniedojadlo** [instrumenta/kubeval#229]
Hi everyone,

First and foremost, I hope that you're all doing well as you can be right now.

I ran into an issue yesterday where I ran kubeval on a simple manifest and returned an error. However, I am running the kubeval against the same manifest today and I am no longer receiving the error. Details below:

I installed kubeval using the following:
Platform/OS:
macOS Mojave Version 10.14.4

brew tap instrumenta/instrumenta
brew install kubeval

First command that I attempted to run against a valid manifest:
```
kubeval test-network-service.yaml                                                                                                                                    ─╯
ERR  - test-network-service.yaml: Failed initalizing schema https://kubernetesjsonschema.dev/master-standalone/service-v1.json: Get https://kubernetesjsonschema.dev/master-standalone/service-v1.json: dial tcp: lookup kubernetesjsonschema.dev on [::1]:53: read udp [::1]:52269->[::1]:53: read: connection refused
```
This returned the error above and I ran the same command today and had zero issues, I wanted to also note that I didn't have any network issues during that period of time:

`kubeval test-network-service.yaml                                                                                                                                    ─╯
PASS - test-network-service.yaml contains a valid Service`

Let me know if I can add anymore details for you,

**Comment by garethr** [comment]
This could have been an intermittent issue with the schema hosting. I'll keep an eye out for other issues, hopefully it doesn't hit you again. Thanks for reporting.
