### ISSUE TITLE
Bump helm plugin

### ISSUE THREAD

**Issue by jkroepke** [instrumenta/kubeval#234]
The helm plugin version is equal to the version of the used kubeval.

Currently, the version of the plugin is 0.13 and the lastest kubeval version is 0.15

I create a PR to bump the version here https://github.com/instrumenta/helm-kubeval/pull/4

The reason why I create an issue here is that https://github.com/instrumenta/helm-kubeval/ looks inactive. No reactions on the lastest pr relates to the 0.14 bump

**Comment by gmacario** [comment]
Hello,

Is there any activity on this issue?
