### ISSUE TITLE
kubeval fails to validate resources using metadata.generateName 

### ISSUE THREAD

**Issue by rslinckx** [instrumenta/kubeval#240]
It seems since commit d793c7bb15c3c5240b7bd37990c5cf93c5f18983 kubeval will attempt to read the resource metadata.name and fails if there is none.

I have a Job resource that uses metadata.generateName instead of a name causing kubeval 0.15 to reject it, while kubeval 0.14 worked fine

**Comment by yannh** [comment]
Hi @rslinckx , could you test against a later release? There is this acceptance tests that should test for this exact case: 
https://github.com/instrumenta/kubeval/blob/master/fixtures/generate_name.yaml

**Comment by rslinckx** [comment]
I can't find any later release than 0.15 ? You mean testing from master ?

**Comment by yannh** [comment]
Yes please!
Note - I'm no maintainer of kubeval so I can't release a new version.

**Comment by rslinckx** [comment]
I'm unfamiliar with building kubeval from source, and the docs seem terse on how to go about it, also there seems no docker image tracking the master commits, so i can't use that either. If you have a quick howto i'll gladly try it out

**Comment by carlossg** [comment]
Fixed in #255
