### ISSUE TITLE
getting ` Failed to decode YAML` Errors

### ISSUE THREAD

**Issue by imranshaik5155** [instrumenta/kubeval#241]
I am trying to run the below command on all of our helm charts

kubeval --ignored-filename-patterns values.yaml -d charts/

but getting a lot of errors like these

`ERR  - Failed to decode YAML from charts/***/templates/deployment.yaml: error converting YAML to JSON: yaml: line 10: could not find expected ':'
ERR  - Failed to decode YAML from charts/*****/templates/service.yaml: error converting YAML to JSON: yaml: did not find expected node content`

can you suggest how can I overcome these

**Comment by yannh** [comment]
Hi @imranshaik5155 , do you think there is a file you could share to reproduce this issue?

**Comment by imranshaik5155** [comment]
HI @yannh 

please find the attached sample file where I am getting the same error while executing kubeval.

is there any way to skip of fix this.
[ingress-test.txt](https://github.com/instrumenta/kubeval/files/4830874/ingress-test.txt)

Thanks
Imran Shaik

**Comment by imranshaik5155** [comment]
HI @yannh ,  any update on this?

**Comment by maxbrunet** [comment]
Getting the same issue with some Grafana dashboards in ConfigMap, here's how to reproduce with Jsonnet:

Install dashboard library (some dashbaords coming from here break, but it is not limited to this source):

```shell
$ jb init
$ jb install github.com/kubernetes-monitoring/kubernetes-mixin
```

Create Jsonnet document:

```jsonnet
// grafana-dashboard-apiserver.jsonnet
local km = import 'github.com/kubernetes-monitoring/kubernetes-mixin/mixin.libsonnet';

{
  apiVersion: 'v1',
  kind: 'ConfigMap',
  metadata: {
    name: 'grafana-dashboard-apiserver',
    namespace: 'grafana',
  },
  data: {
    'apiserver.json': std.manifestJsonEx(km.grafanaDashboards['apiserver.json'], '    '),
  },
}
```

Generate ConfigMap and try to validate:

```shell
$ jsonnet -J vendor grafana-dashboard-apiserver.jsonnet | kubeval
ERR  - Failed to decode YAML from stdin: error converting YAML to JSON: yaml: line 3: did not find expected node content
```

I'm totally able to create this resource with `kubectl apply -f -`.

**Comment by maxbrunet** [comment]
> is there any way to skip or fix this.
> [ingress-test.txt](https://github.com/instrumenta/kubeval/files/4830874/ingress-test.txt)

@ian-howell the file you shared is a Go template, it must be rendered before trying to validate it, e.g.:

```shell
helm template "your-release" charts/your-chart/ | kubeval
```

**Comment by maxbrunet** [comment]
#220 (unreleased) is actually the fix for my issue

**Comment by immusk** [comment]
@maxbrunet I am still facing the same issue. any suggestions on this?

**Comment by carlossg** [comment]
as explained by @maxbrunet the file you shared is a Go template, it must be rendered before trying to validate
