### ISSUE TITLE
customresourcedefinition-apiextensions missing

### ISSUE THREAD

**Issue by philwelz** [instrumenta/kubeval#242]
Hey,

i think both customresourcedefinition-apiextensions are missing. Maybe this is double to  #47.

`apiVersion: apiextensions.k8s.io/v1`
 `apiVersion: apiextensions.k8s.io/v1beta1`  _deprecated since 1.16.0_

It happens in normal mode, strict mode and with version 1.18.0. Kubeval version is 0.15.0 on MacOS and Docker.

```
Failed initializing schema https://kubernetesjsonschema.dev/master-standalone/customresourcedefinition-apiextensions-v1.json
Failed initializing schema https://kubernetesjsonschema.dev/master-standalone/customresourcedefinition-apiextensions-v1beta1.json
Failed initializing schema https://kubernetesjsonschema.dev/master-standalone-strict/customresourcedefinition-apiextensions-v1.json
Failed initializing schema https://kubernetesjsonschema.dev/master-standalone-strict/customresourcedefinition-apiextensions-v1beta1.json
Failed initializing schema https://kubernetesjsonschema.dev/v1.18.0-standalone-strict/customresourcedefinition-apiextensions-v1.json
Failed initializing schema https://kubernetesjsonschema.dev/v1.18.0-standalone-strict/customresourcedefinition-apiextensions-v1beta1.json
```

**Comment by hermanbanken** [comment]
There are no `*-apiextensions*` files in the repository that serves that website:
https://github.com/instrumenta/kubernetes-json-schema.

This seems to be similar, but not identical to #47.
Myself I'm also stuck on this issue.

**Comment by jstrachan** [comment]
FWIW we've added some to this additional repository:

```bash
kubeval --additional-schema-locations https://jenkins-x.github.io/jenkins-x-schemas
```
