### ISSUE TITLE
empty lists cause error about missing metadata

### ISSUE THREAD

**Issue by docwhat** [instrumenta/kubeval#246]
When a `kind: List` is empty (`items` contains no objects) then `kubeval` incorrectly complains about a missing `metadata` key.

```sh
❯ cat empty-list.yaml
---
apiVersion: v1
kind: List
items: []
❯ cat empty-list.yaml | kubeval
ERR  - stdin: Missing 'metadata' key
❯ kubeval --version
Version: 0.15.0
Commit: df50ea7fd4fd202458002a40a6a39ffbb3125bad
Date: 2020-04-14T09:32:50Z
```

**Comment by docwhat** [comment]
Here's a quick patch to add a test:

```patch
diff --git a/fixtures/list_empty_valid.yaml b/fixtures/list_empty_valid.yaml
new file mode 100644
index 0000000..2276fbb
--- /dev/null
+++ b/fixtures/list_empty_valid.yaml
@@ -0,0 +1,4 @@
+---
+apiVersion: v1
+kind: List
+items: []
\ No newline at end of file
diff --git a/kubeval/kubeval_test.go b/kubeval/kubeval_test.go
index d8132d7..b9c9be1 100644
--- a/kubeval/kubeval_test.go
+++ b/kubeval/kubeval_test.go
@@ -34,6 +34,7 @@ func TestValidateValidInputs(t *testing.T) {
 		"extra_property.yaml",
 		"full_domain_group.yaml",
 		"unconventional_keys.yaml",
+		"list_empty_valid.yaml",
 		"list_valid.yaml",
 		"same-object-different-namespace.yaml",
 		"same-object-different-namespace-default.yaml",
```

**Comment by yannh** [comment]
@docwhat This page seems to say that the metadata field is mandatory? https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/#required-fields

**Comment by docwhat** [comment]
Based on kubernetes/kubectl#837, `kind: List` is just union of all the `kind: *List` types.  In 1.19, type `ObjectMeta` says:

> ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.

All the Lists are not persisted; there is no List object stored in the cluster.

**Comment by pgold30** [comment]
@docwhat  hitting this issue now , you know if your fix is going to be merged ?

**Comment by docwhat** [comment]
You'd have to ask the Authors.  I'm just a external user like yourself. 😜
