### ISSUE TITLE
Make field mandatory 

### ISSUE THREAD

**Issue by etiennejournet** [instrumenta/kubeval#265]
Hello !

I was wondering if it was possible to make Kubeval exit if an optionnal field isn't here ?

Like for example make Kubeval exit if there is no probe or no resources for a deployment.

Thanks,

**Comment by yannh** [comment]
Hi @etiennejournet ! Note: I'm not the developer
I think Kubeval's main goal is to verify conformance to the Kubernetes schemas - even then, you probably don't want to make all optional fields mandatory on all resources?
I would recommend you to look at https://github.com/open-policy-agent/conftest (from the same author I think https://garethr.dev/2019/06/introducing-conftest/  ? ) , which enables you to write specific validation rules for your manifests.

**Comment by etiennejournet** [comment]
Hello Yann,

I had a look to it and it seems like that's what I'm looking for. Thanks !

This can be closed.

Regards,
