### ISSUE TITLE
Kubeval Fails with Missing Metadata Key Error

### ISSUE THREAD

**Issue by joesan** [instrumenta/kubeval#266]
I'm facing a very strange issue with kubeval. I have a project where I have used kustomize to template my resources for different environments.

```
joesan@joesan-InfinityBook-S-14-v5:~/Projects/infrastructure-projects/plant-simulator-deployment$ helm template helm | kubeval --strict --force-color --ignore-missing-schemas
WARN - Set to ignore missing schemas
ERR  - plant-simulator-deployment/templates/base/kustomization.yaml: Missing 'metadata' key
ERR  - plant-simulator-deployment/templates/dev/kustomization.yaml: Missing 'metadata' key
ERR  - plant-simulator-deployment/templates/production/kustomization.yaml: Missing 'metadata' key
```

Here is my project: https://github.com/joesan/plant-simulator-deployment (helmify branch)

Unfortunately the error message is not descriptive enough  for me to identify what exactly the error is.

**Comment by yannh** [comment]
Hi @joesan , I would suggest trying to output the result of "helm template helm" to a file, and review whether it is correct?

**Comment by nikdoof** [comment]
Could this be related to #251 and #255? 

It seems that @joesan fixed his issue by adding names, so it could be possible.

**Comment by joesan** [comment]
Yes, I fixed it. There was a template error in one of my files, but the issue is that the error message was not appropriate. I will close this issue.

**Comment by yannh** [comment]
Thanks for updating the ticket @joesan  :)  if you could attach the rendered, broken file, it would help to update kubeval with a better error message. Thanks!
