### ISSUE TITLE
Not valid networking.k8s.io/v1 

### ISSUE THREAD

**Issue by kmaounis** [instrumenta/kubeval#297]
Hi , 

I migrated my ingresses from
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
```
to 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
```
moving my  k8s 1.19 and I am getting 
```
stdin: Failed initializing schema https://kubernetesjsonschema.dev/master-standalone/ingress-networking-v1.json: Could not read schema from HTTP, response status is 404 Not Found
```

using kubeval Version: 0.16.1, If I am not terrible wrong it is a valid yaml
https://kubernetes.io/docs/concepts/services-networking/ingress/
but I do not see it here 
https://github.com/instrumenta/kubernetes-json-schema/tree/master/master-standalone

Do I do something wrong?

**Comment by yannh** [comment]
Hi @kmaounis , Kubeval uses https://github.com/instrumenta/kubernetes-json-schema/ to validate schemas, and schemas for 1.19 and up are missing - see https://github.com/instrumenta/kubernetes-json-schema/issues/26

I am maintaining https://github.com/yannh/kubernetes-json-schema  to solve the issue - it contains instructions on how to use it with kubeval. Hopefully that solves your problem :)

**Comment by kmaounis** [comment]
@yannh , thank you. That was a big help , I missed the part that this repo is not being actively maintained.
```
kubeval --strict --schema-location https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/
```
The above did the trick
