### ISSUE TITLE
Validation passes on service with unknown fields in spec

### ISSUE THREAD

**Issue by dylankb** [instrumenta/kubeval#307]
First of all, thanks for this project. Wanted to leave a bug report but I'm guessing it's a schema issue rather than a kubeval one.

version:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T07:38:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Service is considered valid
```
$ cat my-service.yaml | kubeval
PASS - stdin contains a valid Service (my-service)
```

Note the `foo` field
```
$ cat my-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-service
spec:
  type: ClusterIP
  ports:
    - port: 4665
      targetPort: 4665
      protocol: TCP
      name: http
  selector:
    app: my-service
  foo:
    metadata: 
```

Apply fails
```
$ kubectl -f apply my-service.yaml
error: error validating "my-service.yaml": error validating data: ValidationError(Service.spec): unknown field "foo" in io.k8s.api.core.v1.ServiceSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by yannh** [comment]
Hi @dylankb , try validating with kubeval --strict?

**Comment by dylankb** [comment]
Ah, ok! That option reports the error I expected. 

The [Kubeval docs](https://kubeval.instrumenta.dev/#strict-schemas) gives some context here.
>The Kubernetes API allows for specifying properties on objects that are not part of the schemas. However, kubectl will throw an error if you use it with such files.

But as someone not super knowledgeable about K8s, I'm curious what's the use case for specifying a property as part of a schema if kubectl will reject it later. Anyways I'm closing this issue. Thanks!
