### ISSUE TITLE
Maintenance information

### ISSUE THREAD

**Issue by froblesmartin** [instrumenta/kubeval#353]
Hi! First of all, thanks a lot for the good work done in this project!

I would like to kindly ask the maintainers, if you could shed some light into the project maintenance, and if you are willing to keep working on it, maybe ask for other people to get into it, or just notify that it will not have any further development.

cc @garethr  @carlossg @brendanjryan

**Comment by SVilgelm** [comment]
@carlossg Hi, could you please give us some updates?

I'm interesting in this project and want to see a new release with at least updated dependencies, some of them have the issues and some sub dependencies are already deprecated. It would be great if you can merge all dependabot PRs and release new version.

Thank you!

**Comment by SVilgelm** [comment]
as an example of outdated dependency: this is the only project we use that depends on viper v1.7.1, what still requires deprecated `dgrijalva/jwt-go` and because of this we should keep a replace directive in our `go.mod` file

**Comment by carlossg** [comment]
see https://github.com/instrumenta/kubeval/issues/268#issuecomment-902128481
