### ISSUE TITLE
Type assertion error with bool keys

### ISSUE THREAD

**Issue by Zertsov** [instrumenta/kubeval#91]
In the following yaml, when kubeval goes over it, there's a type assertion error in the `utils.go` for a boolean value. This causes a panic, and therefore should be fixed instead of ending the execution of whatever program is using the lib.

https://pastebin.com/p8TWvL1K

**Comment by Zertsov** [comment]
Note that this is a completely valid YAML file, although not a Kubernetes yaml

**Comment by garethr** [comment]
Thanks for reporting. Could you include the output you see and an example kubernetes config that triggers it? I can add that to the acceptance tests which makes fixing easier.

**Comment by Zertsov** [comment]
The error I get is `panic: interface conversion: interface {} is bool, not string` on the given link I posted with the YAML it failed on.

**Comment by Zertsov** [comment]
So it's not that it's a kubernetes config, but the way the `convertToStringKeys` function is going through that yaml is incorrect, as it's seeing a key as `true` which isn't in the valid pastebin yaml.

**Comment by Zertsov** [comment]
@garethr Any update on this issue? I'm revisiting an old product I wrote and wanted to use this but need this issue resolved first.

**Comment by Zertsov** [comment]
In case anyone else is having this issue, the way I'm working around it is to just recover from the panic and warn the user that it recovered from a panic 🤷‍♂️ 

```Go
defer func() {
	if r := recover(); r != nil {
		logger.Warn("Recovered from panic while validating file: " + path)
	}
}()

results, err := kubeval.Validate(fileContents, path)
...
```

**Comment by garethr** [comment]
This is also the same issue as #98, that one has an int rather than a bool.
