### ISSUE TITLE
When we are using the schema from a file, kubeval should not assume the structure of the file location

### ISSUE THREAD

**Issue by Anuraag-Advani** [instrumenta/kubeval#94]
If we are using a non-default location(or a file), kubeval should not add additional parameters to the schema. `kubernetes-json-schema/master/master-standalone-strict` might get added but a user should have the freedom to use his own file structure

**Comment by garethr** [comment]
Unfortunately the flags mutate the final path. I'd be happy to see a proposal and PR for this if anyone would like to work on it. It would probably need a bit of tidying up of various internal bits however.

**Comment by garethr** [comment]
I'm going to close this due to lack of anyone interested in resolving. I've not heard it causing many issues, please do reopen if you'd be interested in working on a PR for this.
