### ISSUE TITLE
error when validating gitlab helm chart

### ISSUE THREAD

**Issue by jansmets** [instrumenta/kubeval#98]
# Source: gitlab/charts/gitlab/charts/gitlab-shell/templates/nginx-tcp-configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlabsr-nginx-ingress-tcp
  labels: 
    app: gitlab-shell
    chart: gitlab-shell-1.0.2
    release: gitlabsr
    heritage: Tiller
    
data:
  22: "gitlabsr/gitlabsr-gitlab-shell:22"

panic: interface conversion: interface {} is int, not string

goroutine 1 [running]:
github.com/garethr/kubeval/kubeval.convertToStringKeys(0x8455c0, 0xc4203e4ff0, 0xc4201e1668, 0xc420656d08)
 /home/travis/gopath/src/github.com/garethr/kubeval/kubeval/utils.go:13 +0x322
github.com/garethr/kubeval/kubeval.convertToStringKeys(0x8455c0, 0xc4203e4f60, 0x2e559, 0x80ffa0)
 /home/travis/gopath/src/github.com/garethr/kubeval/kubeval/utils.go:13 +0x24f
github.com/garethr/kubeval/kubeval.validateResource(0xc4201ff1bc, 0x13e, 0x2e559, 0x8b9c6d, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
 /home/travis/gopath/src/github.com/garethr/kubeval/kubeval/kubeval.go:130 +0x240
github.com/garethr/kubeval/kubeval.Validate(0xc4201fc000, 0x20592, 0x31715, 0x8b9c6d, 0x5, 0x0, 0x1, 0x43df8b, 0x40, 0x83e720)
 /home/travis/gopath/src/github.com/garethr/kubeval/kubeval/kubeval.go:190 +0x3e5
github.com/garethr/kubeval/cmd.glob..func1(0xb03ac0, 0xb26478, 0x0, 0x0)
 /home/travis/gopath/src/github.com/garethr/kubeval/cmd/root.go:50 +0x6c9
github.com/garethr/kubeval/vendor/github.com/spf13/cobra.(*Command).execute(0xb03ac0, 0xc4200761f0, 0x0, 0x0, 0xb03ac0, 0xc4200761f0)
 /home/travis/gopath/src/github.com/garethr/kubeval/vendor/github.com/spf13/cobra/command.go:766 +0x2b9
github.com/garethr/kubeval/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xb03ac0, 0xc4200b1b80, 0x0, 0x0)
 /home/travis/gopath/src/github.com/garethr/kubeval/vendor/github.com/spf13/cobra/command.go:852 +0x37e
github.com/garethr/kubeval/vendor/github.com/spf13/cobra.(*Command).Execute(0xb03ac0, 0x0, 0xc420140e30)
 /home/travis/gopath/src/github.com/garethr/kubeval/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/garethr/kubeval/cmd.Execute()
 /home/travis/gopath/src/github.com/garethr/kubeval/cmd/root.go:102 +0x31
main.main()
 /home/travis/gopath/src/github.com/garethr/kubeval/main.go:6 +0x20

**Comment by garethr** [comment]
The issue here appears to be that the key is an int not a string and internal functions don't handle this case and panic.

**Comment by garethr** [comment]
This is fixed in #143 and will be in the next release. Thanks for reporting.
